version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
      - ./templates:/app/templates
      - ./static:/app/static
      - ./server.py:/app/server.py
    restart: always